### ISSUE TITLE
Some comments of codes are wrong

### ISSUE THREAD

**Issue by github2016-yuan** [googlesamples/android-MediaEffects#3]
In method of renderResult()

(1)// if no effect is chosen, just render the original bitmap
 mTexRenderer.renderTexture(mTextures[1]);

**should be** 
 // render the result of applyEffect()
 mTexRenderer.renderTexture(mTextures[1]);

(2) // render the result of applyEffect()
mTexRenderer.renderTexture(mTextures[0]);

**should be** 
// if no effect is chosen, just render the original bitmap
mTexRenderer.renderTexture(mTextures[0]);

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
